spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  profiles:
    active: prod

# Configurações adicionais
logging:
  level:
    root: INFO

# Exemplo de configuração de JPA
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
